github:
  pat: ''
  clientId: ''
  clientSecret: ''
reddit:
  clientId: ''
  clientSecret: ''
twitter:
  clientId: ''
  clientSecret: ''
  consumerKey: ''
  consumerSecret: ''
  bearerToken: ''
  accessKey: ''
  accessSecret: ''
  rapidApiKey: ''
